/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utils;
import services.ServiceRdv;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;

import java.awt.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.List;
//import javax.swing.text.Document;

import com.itextpdf.text.Phrase;
import static com.itextpdf.text.pdf.BidiOrder.PDF;
import static com.itextpdf.text.pdf.PdfName.PDF;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.util.Date;
import static javax.print.DocFlavor.BYTE_ARRAY.PDF;
import static javax.print.DocFlavor.INPUT_STREAM.PDF;
import entites.RDV;

/**
 *
 * @author neder
 */
public class PDFRDV {
    
    public void pdfGeneration() throws FileNotFoundException, DocumentException, MalformedURLException, IOException, URISyntaxException {
        Document document = new Document();
        ServiceRdv ps = new ServiceRdv();
        List<RDV> rdvs= ps.affichageRdv();
       File pdfFile = new File ("rdvs.pdf");

        PdfWriter.getInstance(document, new FileOutputStream (pdfFile));
        document.open();
        document.addTitle("RDVs");
        document.addSubject("Using iText");
        document.addKeywords("Java, PDF, iText");
        document.addAuthor("chronicaid");
        document.addCreator("chronicaid admin");
        Paragraph preface = new Paragraph();

        Paragraph titre =new Paragraph (" chronicaid RDVs");
        titre.setAlignment (Element.ALIGN_CENTER);

        // Will create: Report generated by: _name, _date
        preface.add(new Paragraph(
                "ce document est genere par : " + System.getProperty("user.name") + ", " + new Date ()));
        preface.add(new Paragraph(
                "Liste de tous les rendez vous  "));
        preface.setAlignment (Element.ALIGN_CENTER);
        document.add (titre);
        document.add(preface);
      
        // Start a new page
//        document.newPage();

        PDFRDV pdf=new PDFRDV ();
        PdfPTable table = new PdfPTable(6);

        PdfPCell c1 = new PdfPCell(new Phrase("ID"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("date_rdv"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("starttime"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("endtime"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("titre"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

                c1 = new PdfPCell(new Phrase("etat"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);
        

       

        table.setHeaderRows(1);
        for (RDV t:rdvs) {
            table.addCell(String.valueOf (t.getId()));
            table.addCell(String.valueOf (t.getDate_rdv()));
            table.addCell(String.valueOf (t.getStarttime()));
            table.addCell(String.valueOf (t.getEndtime()));
            table.addCell(String.valueOf (t.getTitre()));
                     table.addCell(String.valueOf (t.getEtat()));

            
        }

        document.add (table);
        document.close ();
System.out.println("PDF file location: " + pdfFile.getAbsolutePath());

 }
    
}
